<?php
/**
 * AltaPay Module for Hyva Checkout.
 *
 * Copyright © 2025 AltaPay. All rights reserved.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

?>
<div>
    <script>
        window.addEventListener('checkout:payment:method-activate', event => {
            // console.log(`Selected payment method: ${event.detail.method}`);
        }, {once: true})
    </script>
</div>