<?php
/**
 * AltaPay Module for Hyva Checkout.
 *
 * Copyright © 2025 AltaPay. All rights reserved.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Altapay\HyvaCheckout\ViewModel\TerminalData;

$terminalData = $viewModels->require(TerminalData::class);
$message      = $terminalData->getTerminalData($block->getData('method'));
if ($message) :
    ?>
    <div><?php echo $message; ?></div>
<?php endif; ?>