name: Code Analysis

on:
  push:
    branches:
      - update-wiki
  pull_request:
    branches:
      - update-wiki

jobs:
  code-analysis:
    name: Code Analysis (Magento Standards & PHPStan)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: magento2-hyva-checkout

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv
          coverage: none

      - name: Validate Composer
        working-directory: magento2-hyva-checkout
        run: composer validate --strict

      - name: Install Dependencies
        working-directory: magento2-hyva-checkout
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Locate PHP Code
        working-directory: magento2-hyva-checkout
        run: find src/ -type f -name "*.php"

      - name: Install Magento Coding Standard
        working-directory: magento2-hyva-checkout
        run: |
          composer require --dev magento/magento-coding-standard
          vendor/bin/phpcs --config-set installed_paths vendor/magento/magento-coding-standard

      - name: Run Magento Coding Standard
        working-directory: magento2-hyva-checkout
        run: vendor/bin/phpcs --standard=Magento2 --extensions=php --ignore=vendor,node_modules src/

      - name: Install PHPStan
        working-directory: magento2-hyva-checkout
        run: composer require --dev phpstan/phpstan

      - name: Run PHPStan
        working-directory: magento2-hyva-checkout
        run: vendor/bin/phpstan analyse --level=max --autoload-file=vendor/autoload.php src/
