name: PHP Code Analysis

on:
  pull_request:
    branches: [ update-wiki ]
  push:
    branches: [ update-wiki ]

jobs:
  php-codesniffer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']
    steps:
      - name: Install PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: magento2-hyva-checkout/src

      - name: Configure Composer Allow Plugins
        run: composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install Magento Coding Standard and PHPCompatibility
        run: |
          composer global require \
            magento/magento-coding-standard \
            dealerdirect/phpcodesniffer-composer-installer \
            phpcompatibility/php-compatibility

          # Check if PHPCompatibility exists before cloning
          if [ ! -d "~/.composer/vendor/phpcompatibility/php-compatibility" ]; then
            git clone --depth=1 https://github.com/PHPCompatibility/PHPCompatibility.git ~/.composer/vendor/phpcompatibility/php-compatibility
          fi

          # Register installed paths explicitly
          ~/.composer/vendor/bin/phpcs --config-set installed_paths \
            ~/.composer/vendor/magento/magento-coding-standard,\
            ~/.composer/vendor/phpcompatibility/php-compatibility

          # Verify installed coding standards
          ~/.composer/vendor/bin/phpcs -i

      - name: Run Magento Coding Standard
        run: |
          ~/.composer/vendor/bin/phpcs --standard=Magento2 --ignore=vendor/ .
        working-directory: magento2-hyva-checkout/src
