
name: PHP Code Analysis

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  php-l:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']
    steps:
     - name: Install PHP 7.4
       uses: shivammathur/setup-php@v2
       with:
         php-version: ${{ matrix.php-versions }}
         extensions: intl #optional
         ini-values: "post_max_size=256M" #optional
       
     - run: mkdir magento2-hyva-checkout
     - uses: actions/checkout@v2 
       with: 
         path: magento2-hyva-checkout/src
      
     - name: Run php7.4 linter
       run: |
         find . -path ./vendor -prune -false -o -type f -name '*.php' -print0 | xargs -0 -n1 -P$(nproc) php7.4 -l -n | (! grep -v "No syntax errors detected" )
       working-directory: magento2-hyva-checkout/src
