name: Magento Coding Standards

on:
  push:
    branches:
      - main
      - update-wiki
  pull_request:
    branches:
      - main
      - update-wiki

jobs:
  coding-standard:
    name: Magento Coding Standard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: magento2-hyva-checkout

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Create a Temporary Composer Environment
        run: |
          mkdir -p tools
          cd tools
          composer init --no-interaction
          composer config --no-interaction allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install PHP_CodeSniffer and Magento Coding Standard
        run: |
          cd tools
          composer require --dev magento/magento-coding-standard squizlabs/php_codesniffer
          vendor/bin/phpcs --config-set installed_paths vendor/magento/magento-coding-standard

      - name: Run Magento Coding Standard
        run: |
          tools/vendor/bin/phpcs --standard=Magento2 --extensions=php --ignore=vendor,node_modules magento2-hyva-checkout/src
