name: PHP Code Analysis

on:
  pull_request:
    branches: [ update-wiki ]
  push:
    branches: [ update-wiki ]

jobs:
  php-codesniffer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']
    steps:
     - name: Install PHP ${{ matrix.php-versions }}
       uses: shivammathur/setup-php@v2
       with:
         php-version: ${{ matrix.php-versions }}
         tools: composer

     - name: Checkout Repository
       uses: actions/checkout@v2
       with:
         path: magento2-hyva-checkout/src

     - name: Install Magento Coding Standard
       run: |
         composer global require magento/magento-coding-standard
         phpcs --config-set installed_paths ~/.composer/vendor/magento/magento-coding-standard

     - name: Run Magento Coding Standard
       run: |
         ~/.composer/vendor/bin/phpcs --standard=Magento2 --ignore=vendor/ .
       working-directory: magento2-hyva-checkout/src
