name: PHP Code Analysis

on:
  pull_request:
    branches: [ update-wiki ]
  push:
    branches: [ update-wiki ]

jobs:
  php-codesniffer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']
    steps:
      - name: Install PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: magento2-hyva-checkout/src

      - name: Configure Composer Allow Plugins
        run: composer config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
        working-directory: magento2-hyva-checkout/src

      - name: Install Magento Coding Standard and PHPCompatibility
        run: |
          composer require --dev magento/magento-coding-standard \
                           dealerdirect/phpcodesniffer-composer-installer \
                           phpcompatibility/php-compatibility
          vendor/bin/phpcs --config-set installed_paths vendor/magento/magento-coding-standard,vendor/phpcompatibility/php-compatibility
          vendor/bin/phpcs -i
        working-directory: magento2-hyva-checkout/src

      - name: Run Magento Coding Standard
        run: |
          vendor/bin/phpcs --standard=Magento2 --ignore=vendor/ .
        working-directory: magento2-hyva-checkout/src
